{"name": "错误账号密码", "status": "passed", "description": "这是测试用例用例2的描述信息", "start": 1625451161503, "stop": 1625451171959, "uuid": "ad00bd4d-e00a-41d6-afd3-82b189e49533", "historyId": "9078c34ff831bb74ca4c0c76bfe75e29", "testCaseId": "92e7901b1cae8655b4042e7eeb0890dd", "fullName": "testCase.test.Testcase#test_case02", "labels": [{"name": "story", "value": "登录模块下的子模块:错误登录账号密码"}, {"name": "feature", "value": "登录模块"}, {"name": "parentSuite", "value": "testCase"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "Testcase"}, {"name": "host", "value": "XSD-20190315NRK"}, {"name": "thread", "value": "5004-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testCase.test"}]}